seed: 1234

bert_name: "/home/wpf/pretrain_model/bert-base-uncased/"
vit_name: "/home/wpf/pretrain_model/clip-vit-base-patch32/"
# vit_name: "/home/wpf/pretrain_model/CLIP-ViT-B-32-laion2B-s34B-b79K/"
device: cuda:0

batch_size: 32

max_seq: 40
aux_size: 128
rcnn_size: 64
ignore_idx: 0

load_path:  null
dataset_name: 'twitter15'